tables:
  - accounts
  - body_sites
  - case_types
  - cassette_colors
  - cbc_measurements
  - control_code_types
  - dx_classifications
  - dx_sub_classifications
  - flow_intensities
  - flow_marker_types
  - flow_markers
  - flow_specimen_panel_units
  - heme_descriptions
  - heme_interpretation_tests
  - heme_panel_exceptions
  - ihc_specimen_transports
  - ihc_specimen_types
  - image_types
  - locations
  - marital_statuses
  - pc_tests
  - race_types
  - specimen_types
  - specialties
  - tc_accounts
  - tc_case_types
  - tc_linkings
  - tc_locations
  - tc_specimen_types
  - tc_linkings
