tables:
  - account_preferences
  - accounts
  - accounts_case_types
  - client_accounts
  - client_account_locations
  - client_account_locations_client_account_physicians
  - client_account_physicians
  - client_account_location_report_preferences
  - client_account_todos
  - accounts_delivery_methods
  - amendment_reasons
  - body_site_specimen_maps
  - body_sites
  - body_sites_specimen_types
  - bolt_on_types
  - bolton_sort_orders
  - business_categories
  - business_categories_business_reports
  - business_reports
  - business_reports_accounts
  - business_reports_user_favorites
  - business_reports_users
  - case_type_grossing_elements
  - case_type_prefixes
  - case_types
  - case_types_specimen_types
  - cases_pap_reflex_rules
  - cassette_colors
  - cassette_print_outlets
  - cbc_code_groups
  - cbc_codes
  - conditions
  - configurables
  - control_code_types
  - cpt_billing_unit_rules
  - cpt_code_rules
  - cytology_descriptions
  - cytology_differentials
  - default_amendment_reasons
  - default_qa_categories
  - default_qa_flags
  - default_roles
  - default_roles_permissions
  - delivery_methods
  - disclaimer_types
  - disclaimers
  - dx_classifications
  - dx_sub_classifications
  - dyk_faqs
  - dyk_types
  - dyks
  - file_types
  - flow_groups
  - flow_intensities
  - flow_marker_types
  - flow_markers
  - flow_population_types
  - genders
  - global_delivery_rules
  - grossing_elements
  - ihc_algorithms
  - ihc_specimen_types
  - ihc_transport_types
  - item_questions
  - labis_faqs
  - list_values
  - list_values_pap_reflex_rules
  - lists
  - locations
  - marital_statuses
  - mediums
  - order_entry_questions
  - pap_queues
  - pap_reflex_rules
  - pathologist_sign_out_codes
  - patient_insurances
  - payer_plans
  - payers
  - permission_categories
  - permissions
  - permissions_roles
  - qa_categories
  - question_types
  - questions
  - races
  - referring_physicians
  - relationships
  - report_templates
  - report_types
  - roles
  - roles_users
  - screen_types
  - specialties
  - specimen_clarities
  - specimen_colors
  - specimen_cycles
  - specimen_test_categories
  - specimen_test_panel_components
  - specimen_test_types
  - specimen_tests
  - specimen_types
  - specimen_types_tests
  - specimen_types_variable_fields
  - stain_preorder_preferences
  - stain_preorder_preferences_tests
  - states
  - support_categories
  - support_users
  - user_preferences
  - users
  - variable_fields
  - work_station_types
  - work_stations
