# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4af8d4a5680ffa9103c35109ea4260d9136050a234cefdb42c622a8657af9685170af147712152a38b138136dc9f19bbf5812d651c1ae1c111d23b8e8173035

test:
  secret_key_base: 8fba90844f75d232c03a2febfcc5bd90dc6a5878335597e30eff7a31205adb7aacaa6e7930528cdc6614f157522af4bd83bac606c11edd61ebb0e5cafb051770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
