Object.const_set("ClientAccountLocationReportPreference", Class.new(ActiveRecord::Base))
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>2, "display_requisition_number"=>true})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>58})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>115, "show_icd9"=>true, "display_requisition_number"=>true})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>119})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>164})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>174})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>179})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>376, "show_icd9"=>true, "display_requisition_number"=>true})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>63})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>389, "mask_ssn"=>true})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>412, "mask_ssn"=>true})
ClientAccountLocationReportPreference.find_or_create_by({"client_account_location_id"=>431})
