Object.const_set("AmendmentReason", Class.new(ActiveRecord::Base))
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>1, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>1, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>1, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>1, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>2, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>2, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>2, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>2, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>3, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>3, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>3, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>3, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>4, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>4, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>4, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>4, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>5, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>5, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>5, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>5, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>6, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>6, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>6, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>6, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>7, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>7, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>7, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>7, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>8, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>8, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>8, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>8, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>9, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>9, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>9, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>9, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>10, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>10, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>10, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>10, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>11, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>11, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>11, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>11, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>12, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>12, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>12, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>12, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>13, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>13, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>13, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>13, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>14, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>14, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>14, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>14, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>15, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>15, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>15, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>15, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>16, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>16, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>16, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>16, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>17, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>17, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>17, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>17, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>18, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>18, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>18, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>18, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>19, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>19, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>19, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>19, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>20, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>20, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>20, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>20, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>21, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>21, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>21, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>21, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>22, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>22, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>22, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>22, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>23, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>23, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>23, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>23, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>24, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>24, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>24, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>24, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>25, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>25, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>25, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>25, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>26, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>26, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>26, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>26, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>27, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>27, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>27, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>27, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>28, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>28, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>28, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>28, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>29, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>29, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>29, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>29, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>30, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>30, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>30, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>30, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>31, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>31, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>31, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>31, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>32, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>32, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>32, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>32, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>33, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>33, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>33, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>33, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>34, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>34, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>34, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>34, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>35, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>35, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>35, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>35, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>36, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>36, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>36, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>36, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>37, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>37, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>37, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>37, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>38, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>38, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>38, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>38, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>39, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>39, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>39, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>39, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>40, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>40, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>40, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>40, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>41, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>41, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>41, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>41, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>42, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>42, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>42, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>42, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>43, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>43, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>43, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>43, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>44, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>44, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>44, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>44, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>45, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>45, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>45, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>45, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>46, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>46, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>46, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>46, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>47, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>47, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>47, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>47, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>48, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>48, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>48, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>48, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>49, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>49, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>49, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>49, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>50, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>50, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>50, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>50, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>51, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>51, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>51, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>51, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>52, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>52, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>52, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>52, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>53, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>53, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>53, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>53, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>54, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>54, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>54, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>54, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>55, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>55, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>55, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>55, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>56, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>56, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>56, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>56, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>57, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>57, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>57, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>57, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>58, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>58, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>58, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>58, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>59, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>59, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>59, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>59, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>60, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>60, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>60, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>60, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>61, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>61, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>61, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>61, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>62, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>62, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>62, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>62, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>63, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>63, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>63, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>63, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>64, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>64, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>64, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>64, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>65, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>65, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>65, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>65, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>66, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>66, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>66, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>66, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>67, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>67, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>67, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>67, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>68, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>68, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>68, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>68, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>69, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>69, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>69, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>69, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>70, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>70, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>70, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>70, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>71, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>71, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>71, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>71, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>72, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>72, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>72, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>72, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>73, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>73, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>73, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>73, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>74, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>74, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>74, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>74, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>75, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>75, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>75, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>75, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>76, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>76, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>76, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>76, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>77, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>77, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>77, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>77, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>78, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>78, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>78, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>78, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>79, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>79, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>79, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>79, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>80, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>80, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>80, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>80, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>81, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>81, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>81, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>81, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>82, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>82, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>82, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>82, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>83, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>83, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>83, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>83, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>84, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>84, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>84, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>84, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>85, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>85, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>85, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>85, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>86, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>86, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>86, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>86, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>87, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>87, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>87, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>87, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>88, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>88, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>88, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>88, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>89, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>89, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>89, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>89, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>90, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>90, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>90, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>90, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>91, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>91, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>91, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>91, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>92, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>92, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>92, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>92, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>93, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>93, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>93, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>93, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>94, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>94, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>94, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>94, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>95, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>95, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>95, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>95, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>96, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>96, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>96, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>96, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>97, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>97, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>97, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>97, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>98, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>98, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>98, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>98, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>99, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>99, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>99, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>99, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>100, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>100, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>100, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>100, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>101, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>101, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>101, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>101, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>102, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>102, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>102, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>102, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>103, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>103, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>103, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>103, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>104, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>104, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>104, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>104, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>105, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>105, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>105, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>105, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>106, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>106, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>106, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>106, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>107, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>107, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>107, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>107, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>108, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>108, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>108, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>108, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>109, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>109, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>109, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>109, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>110, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>110, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>110, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>110, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clerical Error", "account_id"=>111, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Clinical Error", "account_id"=>111, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Additional diagnostic material", "account_id"=>111, "active"=>true, "default"=>true})
AmendmentReason.find_or_create_by({"description"=>"Other", "account_id"=>111, "active"=>true, "default"=>true})
