Object.const_set("BoltOnType", Class.new(ApplicationRecord))
BoltOnType.find_or_create_by({"description"=>"Dipstick"})
BoltOnType.find_or_create_by({"description"=>"Cytology"})
BoltOnType.find_or_create_by({"description"=>"FISH"})
BoltOnType.find_or_create_by({"description"=>"BreathTek", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"Prostate", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"Heme Flow", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"IHC", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"Frozen", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"Morphology", "is_required"=>true})
BoltOnType.find_or_create_by({"description"=>"FISHOnc"})
BoltOnType.find_or_create_by({"description"=>"Molecular"})
