Object.const_set("CassetteColor", Class.new(ApplicationRecord))
CassetteColor.find_or_create_by({"description"=>"Aqua", "carousel_number"=>1})
CassetteColor.find_or_create_by({"description"=>"Blue", "carousel_number"=>2})
CassetteColor.find_or_create_by({"description"=>"Gray", "carousel_number"=>3})
CassetteColor.find_or_create_by({"description"=>"Lilac", "carousel_number"=>4})
CassetteColor.find_or_create_by({"description"=>"Orange", "carousel_number"=>5})
CassetteColor.find_or_create_by({"description"=>"Peach", "carousel_number"=>6})
CassetteColor.find_or_create_by({"description"=>"Pink", "carousel_number"=>7})
CassetteColor.find_or_create_by({"description"=>"Red", "carousel_number"=>8})
CassetteColor.find_or_create_by({"description"=>"Tan", "carousel_number"=>9})
CassetteColor.find_or_create_by({"description"=>"White", "carousel_number"=>10})
CassetteColor.find_or_create_by({"description"=>"Yellow", "carousel_number"=>11})
CassetteColor.find_or_create_by({"description"=>"Green", "carousel_number"=>12})
CassetteColor.find_or_create_by({"description"=>"Flo Pink", "carousel_number"=>13})
