Object.const_set("CbcCode", Class.new(ApplicationRecord))
CbcCode.find_or_create_by({"code"=>"WBC", "unit"=>"K/ul", "maximum"=>500, "precision"=>1, "order"=>1, "active"=>true, "report_order"=>1})
CbcCode.find_or_create_by({"code"=>"Hgb", "unit"=>"g/dL", "maximum"=>100, "precision"=>1, "order"=>2, "active"=>true, "report_order"=>7})
CbcCode.find_or_create_by({"code"=>"Hct", "has_percent"=>true, "maximum"=>100, "precision"=>1, "order"=>3, "active"=>true, "report_order"=>8})
CbcCode.find_or_create_by({"code"=>"MCV", "unit"=>"fL", "maximum"=>200, "precision"=>1, "order"=>4, "active"=>true, "report_order"=>9})
CbcCode.find_or_create_by({"code"=>"RDW", "has_percent"=>true, "maximum"=>100, "precision"=>1, "order"=>5, "active"=>true, "report_order"=>10})
CbcCode.find_or_create_by({"code"=>"PLT", "unit"=>"K/ul", "maximum"=>2000, "precision"=>0, "order"=>6, "active"=>true, "report_order"=>11})
CbcCode.find_or_create_by({"code"=>"Basophils", "unit"=>"K/ul", "has_percent"=>true, "maximum"=>999, "precision"=>1, "cbc_code_group_id"=>1, "order"=>7, "active"=>true, "report_order"=>2})
CbcCode.find_or_create_by({"code"=>"Eosinophils", "unit"=>"K/ul", "has_percent"=>true, "maximum"=>999, "precision"=>1, "cbc_code_group_id"=>1, "order"=>8, "active"=>true, "report_order"=>3})
CbcCode.find_or_create_by({"code"=>"Lymphocytes", "unit"=>"K/ul", "has_percent"=>true, "maximum"=>999, "precision"=>1, "cbc_code_group_id"=>1, "order"=>9, "active"=>true, "report_order"=>4})
CbcCode.find_or_create_by({"code"=>"Monocytes", "unit"=>"K/ul", "has_percent"=>true, "maximum"=>999, "precision"=>1, "cbc_code_group_id"=>1, "order"=>10, "active"=>true, "report_order"=>5})
CbcCode.find_or_create_by({"code"=>"Neutrophils", "unit"=>"K/ul", "has_percent"=>true, "maximum"=>999, "precision"=>1, "cbc_code_group_id"=>1, "order"=>11, "active"=>true, "report_order"=>6})
