Object.const_set("CptCodeRule", Class.new(ActiveRecord::Base))
CptCodeRule.find_or_create_by({"name"=>"fcin - Rule 1", "originating_test"=>1668, "swapping_tests"=>"733", "control_code_id"=>34873, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"fcis - Rule 1", "originating_test"=>1668, "swapping_tests"=>"733", "control_code_id"=>34874, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"anglip - Rule 1", "originating_test"=>1668, "swapping_tests"=>"733", "control_code_id"=>34890, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"lip - Rule 1", "originating_test"=>1668, "swapping_tests"=>"733", "control_code_id"=>34889, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"tag - Rule 1", "originating_test"=>1668, "swapping_tests"=>"733", "control_code_id"=>34899, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"dermatolip - Rule 1", "originating_test"=>1668, "swapping_tests"=>"1321", "control_code_id"=>39496, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"mul - Rule 1", "originating_test"=>2830, "swapping_tests"=>"5969", "control_code_id"=>41643, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"mel - Rule 1", "originating_test"=>924, "swapping_tests"=>"5881", "control_code_id"=>39650, "account_id"=>99, "created_by"=>705, "rule_number"=>2})
CptCodeRule.find_or_create_by({"name"=>"ANAST ESOPHAGO-ENTERIC CHRONIC - Rule 1", "originating_test"=>723, "swapping_tests"=>"742", "control_code_id"=>39651, "account_id"=>27, "created_by"=>308, "rule_number"=>2})
