Object.const_set("DefaultRole", Class.new(ActiveRecord::Base))
DefaultRole.find_or_create_by({"description"=>"Administrator"})
DefaultRole.find_or_create_by({"description"=>"Accessioner"})
DefaultRole.find_or_create_by({"description"=>"Grosser"})
DefaultRole.find_or_create_by({"description"=>"Special Studies Tech"})
DefaultRole.find_or_create_by({"description"=>"Lab Tech"})
DefaultRole.find_or_create_by({"description"=>"Account Manager"})
DefaultRole.find_or_create_by({"description"=>"Pathologist"})
DefaultRole.find_or_create_by({"description"=>"QA Specialist"})
DefaultRole.find_or_create_by({"description"=>"Billing Rep"})
DefaultRole.find_or_create_by({"description"=>"Transcriptionist"})
