Object.const_set("DeliveryMethod", Class.new(ActiveRecord::Base))
DeliveryMethod.find_or_create_by({"name"=>"Remote Print", "validation_expression"=>"None", "is_active"=>true, "tps_id"=>"f9c9f777-f422-4926-8024-0ffc9eae8fb6"})
DeliveryMethod.find_or_create_by({"name"=>"IP Remote Print", "validation_expression"=>"None", "is_active"=>true, "tps_id"=>"a9f621d2-9845-46d6-9e6a-7f492766f9d8"})
DeliveryMethod.find_or_create_by({"name"=>"Print", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true, "print_required"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Fax", "validation_expression"=>"Fax", "is_user_configurable"=>true, "is_active"=>true, "tps_id"=>"be520a40-70e7-432f-90d9-d46bb864ca45"})
DeliveryMethod.find_or_create_by({"name"=>"MyCBLPath.com", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true, "tps_id"=>"242E8D0C-0C6B-DE11-B3D5-000BDB90B5AB"})
DeliveryMethod.find_or_create_by({"name"=>"Emdeon", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"AllScripts", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Provation", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Medent", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"MdReports", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"My.Labis.Net", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Greenway", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"gMed4", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"UroChart", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Meridian", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"STI", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"eMedPractice", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"GECentricity", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"GECentricityPDF", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"eClinicals", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"eClinicals2", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"Praxis", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"LabISPDF", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"UroChart2", "validation_expression"=>"None", "is_user_configurable"=>true, "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"AtlasIon", "validation_expression"=>"None", "is_active"=>true})
DeliveryMethod.find_or_create_by({"name"=>"AtlasLabworks", "validation_expression"=>"None", "is_active"=>true})
