Object.const_set("FlowIntensity", Class.new(ActiveRecord::Base))
FlowIntensity.find_or_create_by({"description"=>"Bright"})
FlowIntensity.find_or_create_by({"description"=>"Dim"})
FlowIntensity.find_or_create_by({"description"=>"Dim-Moderate"})
FlowIntensity.find_or_create_by({"description"=>"Moderate"})
FlowIntensity.find_or_create_by({"description"=>"Moderate-Bright"})
FlowIntensity.find_or_create_by({"description"=>"Negative"})
FlowIntensity.find_or_create_by({"description"=>"Biphasic"})
FlowIntensity.find_or_create_by({"description"=>"Examined"})
FlowIntensity.find_or_create_by({"description"=>"Indeterminate"})
