Object.const_set("Gender", Class.new(ApplicationRecord))
Gender.find_or_create_by({"description"=>"M", "value"=>"m"})
Gender.find_or_create_by({"description"=>"F", "value"=>"f"})
Gender.find_or_create_by({"description"=>"H", "value"=>"h"})
Gender.find_or_create_by({"description"=>"T", "value"=>"t"})
