Object.const_set("GrossingElement", Class.new(ApplicationRecord))
GrossingElement.find_or_create_by({"name"=>"specimen size", "element_type"=>"text field:small", "variable_field_id"=>9})
GrossingElement.find_or_create_by({"name"=>"specimen color", "element_type"=>"select:color", "variable_field_id"=>5})
GrossingElement.find_or_create_by({"name"=>"number of pieces", "element_type"=>"text field:small:number", "variable_field_id"=>8})
GrossingElement.find_or_create_by({"name"=>"number of cassettes", "element_type"=>"text field:small:number", "variable_field_id"=>2})
GrossingElement.find_or_create_by({"name"=>"number of slides", "element_type"=>"text field:small:number", "variable_field_id"=>10})
GrossingElement.find_or_create_by({"name"=>"clarity", "element_type"=>"text field:small", "variable_field_id"=>4})
GrossingElement.find_or_create_by({"name"=>"medium", "element_type"=>"text field:medium", "variable_field_id"=>11})
GrossingElement.find_or_create_by({"name"=>"cassette label", "element_type"=>"text field:medium", "variable_field_id"=>1})
GrossingElement.find_or_create_by({"name"=>"cassette color", "element_type"=>"select:color", "variable_field_id"=>3})
GrossingElement.find_or_create_by({"name"=>"cycle", "element_type"=>"text field:small", "variable_field_id"=>6})
GrossingElement.find_or_create_by({"name"=>"control code", "element_type"=>"select:control codes"})
GrossingElement.find_or_create_by({"name"=>"comments", "element_type"=>"text area"})
GrossingElement.find_or_create_by({"name"=>"weight", "element_type"=>"text field:small", "variable_field_id"=>17})
GrossingElement.find_or_create_by({"name"=>"cO2", "element_type"=>"text field:small", "variable_field_id"=>16})
GrossingElement.find_or_create_by({"name"=>"conclusion", "element_type"=>"select:conclusion"})
GrossingElement.find_or_create_by({"name"=>"ThinPrep", "element_type"=>"text field:small"})
GrossingElement.find_or_create_by({"name"=>"CytoSpin", "element_type"=>"text field:small"})
GrossingElement.find_or_create_by({"name"=>"Smears", "element_type"=>"text field:small"})
GrossingElement.find_or_create_by({"name"=>"fluid volume", "element_type"=>"text field:small"})
GrossingElement.find_or_create_by({"name"=>"Time of Fixation", "element_type"=>"text field:small"})
GrossingElement.find_or_create_by({"name"=>"Time of Processing", "element_type"=>"text field:small"})
