Object.const_set("IhcAlgorithm", Class.new(ApplicationRecord))
IhcAlgorithm.find_or_create_by({"description"=>"IHC Nuclear v1", "algorithm_type"=>"Nuclear"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC ER Breast Dako Clone1D5 v1", "algorithm_type"=>"Nuclear"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC PR Breast Dako ClonePgR636 v1", "algorithm_type"=>"Nuclear"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC PR Breast v1", "algorithm_type"=>"Nuclear"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC ER Breast v1", "algorithm_type"=>"Nuclear"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC Membrane v1", "algorithm_type"=>"Membrane"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC HER2 Breast Dako HercepTest v1", "algorithm_type"=>"Membrane"})
IhcAlgorithm.find_or_create_by({"description"=>"IHC HER2 Breast v1", "algorithm_type"=>"Membrane"})
