Object.const_set("PapQueue", Class.new(ActiveRecord::Base))
PapQueue.find_or_create_by({"description"=>"Mandatory"})
PapQueue.find_or_create_by({"description"=>"Retrospective"})
PapQueue.find_or_create_by({"description"=>"QA"})
PapQueue.find_or_create_by({"description"=>"Pathologist"})
PapQueue.find_or_create_by({"description"=>"HPV"})
