Object.const_set("Permission", Class.new(ActiveRecord::Base))
Permission.find_or_create_by({"description"=>"Sign Out Case", "tooltip"=>"Allows users to sign out cases."})
Permission.find_or_create_by({"description"=>"Edit Case", "tooltip"=>"Allows users to edit existing case information from case summary."})
Permission.find_or_create_by({"description"=>"Refer Case", "tooltip"=>"Allows users to refer cases to CBLPath."})
Permission.find_or_create_by({"description"=>"Special Procedures", "tooltip"=>"Allows users to add/edit/cancel special procedure orders on a case."})
Permission.find_or_create_by({"description"=>"Manage Gross Codes", "tooltip"=>"Allows users to manage gross/laboratory codes used in grossing."})
Permission.find_or_create_by({"description"=>"Client Management", "tooltip"=>"Allows users to manage client accounts, locations, physicians, referring physicians, and delivery settings."})
Permission.find_or_create_by({"description"=>"Accession", "tooltip"=>"Allows users to accession new cases."})
Permission.find_or_create_by({"description"=>"Gross", "tooltip"=>"Allows users to gross cases, edit specimen information, and upload gross images."})
Permission.find_or_create_by({"description"=>"View Case", "tooltip"=>"Allows users to view case information (excluding diagnostic information) in read-only mode."})
Permission.find_or_create_by({"description"=>"View Client", "tooltip"=>"Allows users to view client account information in read-only mode."})
Permission.find_or_create_by({"description"=>"Prescreen Case", "tooltip"=>"Allows users to prescreen cases in pathology."})
Permission.find_or_create_by({"description"=>"Edit Diagnostic", "tooltip"=>"Allows users to enter and edit diagnostic information."})
Permission.find_or_create_by({"description"=>"View Diagnostic", "tooltip"=>"Allows users to view case diagnostic information in read only mode."})
Permission.find_or_create_by({"description"=>"Delete Case", "tooltip"=>"Allows users to delete cases."})
Permission.find_or_create_by({"description"=>"Resolve Flags", "tooltip"=>"Allows users to resolve QA flags and incidents."})
Permission.find_or_create_by({"description"=>"Manage Flags", "tooltip"=>"Allows users to manage QA flags."})
Permission.find_or_create_by({"description"=>"Reactivate Case", "tooltip"=>"Allows users to reactivate a deleted case."})
Permission.find_or_create_by({"description"=>"Issue Preliminary Report", "tooltip"=>"Allows users to create a preliminary report for a case."})
Permission.find_or_create_by({"description"=>"Billing", "tooltip"=>"Allows users access to the billing dashboard, approve cases for billing, hold cases from billing, download billing files, and maintain payers."})
Permission.find_or_create_by({"description"=>"Account Admin", "tooltip"=>"Allows users access to Site Admin to set up additional users and manage locations and roles."})
Permission.find_or_create_by({"description"=>"Special Studies", "tooltip"=>"Allows users to access to the special studies lab."})
Permission.find_or_create_by({"description"=>"Manage Pathology Codes", "tooltip"=>"Allows user to manage diagnostic and cytology codes."})
Permission.find_or_create_by({"description"=>"Lab Reports", "tooltip"=>"Allows users to execute business reports for laboratory processing."})
Permission.find_or_create_by({"description"=>"Client Center Reports", "tooltip"=>"Allows users to execute business reports for client center."})
Permission.find_or_create_by({"description"=>"Change Status", "tooltip"=>"Allows user to change the status of a case."})
Permission.find_or_create_by({"description"=>"Pathology Reports", "tooltip"=>"Allows users to execute business reports for pathology."})
Permission.find_or_create_by({"description"=>"QA Reports", "tooltip"=>"Allows users to execute business reports for QA."})
Permission.find_or_create_by({"description"=>"Billing Reports", "tooltip"=>"Allows users to execute business reports for billing."})
Permission.find_or_create_by({"description"=>"Delete Electronic Orders", "tooltip"=>"Allow users to delete electronic orders."})
Permission.find_or_create_by({"description"=>"Amend Case", "tooltip"=>"Allows users to amend a case."})
Permission.find_or_create_by({"description"=>"Assign Case", "tooltip"=>"Allows users to assign or reassign a case to a Pathologist."})
Permission.find_or_create_by({"description"=>"Redeliver Reports", "tooltip"=>"Allow users to redeliver reports."})
