Object.const_set("QaCategory", Class.new(ActiveRecord::Base))
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>1})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Patient Information", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Specimen", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>3})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Patient Information", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Specimen", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>5})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>16})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>16})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>16})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>16})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>11})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>11})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>11})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>11})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>1})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>1})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>1})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>18})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>18})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>18})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>18})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>19})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>19})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>19})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>19})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>14})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>14})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>14})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>14})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>20})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>20})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>20})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>20})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>21})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>21})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>21})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>21})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>22})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>22})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>22})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>22})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>23})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>23})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>23})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>23})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>24})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>24})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>24})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>24})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>25})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>25})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>25})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>25})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>26})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>26})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>26})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>26})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>27})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>27})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>27})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>27})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>28})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>28})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>28})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>28})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>29})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>29})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>29})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>29})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>6})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>6})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>6})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>6})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>30})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>30})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>30})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>30})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>31})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>31})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>31})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>31})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>32})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>32})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>32})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>32})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>33})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>33})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>33})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>33})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>34})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>34})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>34})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>34})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>35})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>35})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>35})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>35})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>36})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>36})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>36})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>36})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>37})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>37})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>37})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>37})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>38})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>38})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>38})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>38})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>39})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>39})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>39})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>39})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>40})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>40})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>40})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>40})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>41})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>41})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>41})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>41})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>43})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>43})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>43})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>43})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>44})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>44})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>44})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>44})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>45})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>45})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>45})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>45})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>46})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>46})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>46})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>46})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>47})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>47})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>47})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>47})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>49})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>49})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>49})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>49})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>50})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>50})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>50})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>50})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>51})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>51})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>51})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>51})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>52})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>52})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>52})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>52})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>53})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>53})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>53})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>53})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>54})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>54})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>54})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>54})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>55})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>55})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>55})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>55})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>56})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>56})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>56})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>56})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>57})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>57})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>57})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>57})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>58})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>58})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>58})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>58})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>59})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>59})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>59})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>59})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>60})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>60})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>60})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>60})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>61})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>61})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>61})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>61})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>62})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>62})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>62})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>62})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>63})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>63})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>63})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>63})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>64})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>64})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>64})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>64})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>65})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>65})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>65})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>65})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>66})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>66})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>66})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>66})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>67})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>67})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>67})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>67})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>69})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>69})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>69})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>69})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>70})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>70})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>70})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>70})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>71})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>71})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>71})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>71})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>74})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>74})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>74})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>74})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>76})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>76})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>76})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>76})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>77})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>77})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>77})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>77})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>78})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>78})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>78})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>78})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>80})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>80})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>80})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>80})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>81})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>81})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>81})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>81})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>82})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>82})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>82})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>82})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>83})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>83})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>83})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>83})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>84})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>84})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>84})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>84})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>85})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>85})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>85})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>85})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>86})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>86})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>86})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>86})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>87})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>87})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>87})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>87})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>88})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>88})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>88})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>88})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>89})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>89})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>89})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>89})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>90})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>90})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>90})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>90})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>91})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>91})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>91})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>91})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>92})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>92})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>92})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>92})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>93})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>93})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>93})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>93})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>94})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>94})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>94})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>94})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>96})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>96})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>96})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>96})
QaCategory.find_or_create_by({"description"=>"Pathologist review", "account_id"=>93})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>98})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>98})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>98})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>98})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>99})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>99})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>99})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>99})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>100})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>100})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>100})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>100})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>101})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>101})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>101})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>101})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>102})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>102})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>102})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>102})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>103})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>103})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>103})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>103})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>104})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>104})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>104})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>104})
QaCategory.find_or_create_by({"description"=>"Diagnostic QA", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Post report sign out", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Quality management", "account_id"=>97})
QaCategory.find_or_create_by({"description"=>"Quality Mangement", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"External review AGREE", "account_id"=>95})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>106})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>106})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>106})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>106})
QaCategory.find_or_create_by({"description"=>"Requisition Issues", "account_id"=>108})
QaCategory.find_or_create_by({"description"=>"Data Entry Issues", "account_id"=>108})
QaCategory.find_or_create_by({"description"=>"Specimen Processing", "account_id"=>108})
QaCategory.find_or_create_by({"description"=>"Lab Processing Errors", "account_id"=>108})
QaCategory.find_or_create_by({"description"=>"Pathology Issues", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"Other", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Reporting", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Lab Errors", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"Specimen Rejections", "account_id"=>42})
QaCategory.find_or_create_by({"description"=>"QA Bi-annual review", "account_id"=>107})
QaCategory.find_or_create_by({"description"=>"Incorrect birth date entered", "account_id"=>48})
QaCategory.find_or_create_by({"description"=>"CBLlPath Additional Studies", "account_id"=>27})
QaCategory.find_or_create_by({"description"=>"Outside Consults", "account_id"=>42})
