Object.const_set("Question", Class.new(ActiveRecord::Base))
Question.find_or_create_by({"question_type_id"=>4, "question_text"=>"Please provide diagnosis under consideration.", "required"=>true})
Question.find_or_create_by({"question_type_id"=>4, "question_text"=>"Please provide ICD9 under consideration.", "required"=>true, "validation"=>"icd9"})
Question.find_or_create_by({"question_type_id"=>5, "title"=>"Paraffin Block;Prepared Slide;Other", "question_text"=>"In what form are the specimen(s) being submitted?", "required"=>true})
Question.find_or_create_by({"question_type_id"=>1, "title"=>"Yes;No", "question_text"=>"Would you like to receive digital slides for this order?", "required"=>true})
Question.find_or_create_by({"question_type_id"=>1, "title"=>"Yes;No", "question_text"=>"Would you like this to be a digital consult?", "required"=>true})
Question.find_or_create_by({"question_type_id"=>4, "question_text"=>"# of slides being sent", "required"=>true})
Question.find_or_create_by({"question_type_id"=>4, "question_text"=>"# of blocks being sent", "required"=>true})
Question.find_or_create_by({"question_type_id"=>4, "question_text"=>"# of other materials being sent", "required"=>true})
