Object.const_set("Race", Class.new(ActiveRecord::Base))
Race.find_or_create_by({"description"=>"White or Caucasian"})
Race.find_or_create_by({"description"=>"Native Hawaiian, Pacific Islander"})
Race.find_or_create_by({"description"=>"Middle Eastern or North African"})
Race.find_or_create_by({"description"=>"African American, Black"})
Race.find_or_create_by({"description"=>"Native American, Alaskan Native"})
Race.find_or_create_by({"description"=>"Hispanic, Latino"})
Race.find_or_create_by({"description"=>"Other race"})
Race.find_or_create_by({"description"=>"Asian, Including Indian Subcontinent"})
Race.find_or_create_by({"description"=>"Unspecified"})
