Object.const_set("SpecimenClarity", Class.new(ActiveRecord::Base))
SpecimenClarity.find_or_create_by({"description"=>"cloudy"})
SpecimenClarity.find_or_create_by({"description"=>"other"})
SpecimenClarity.find_or_create_by({"description"=>"turbid"})
SpecimenClarity.find_or_create_by({"description"=>"clear"})
SpecimenClarity.find_or_create_by({"description"=>"dark clear"})
SpecimenClarity.find_or_create_by({"description"=>"light turbid"})
SpecimenClarity.find_or_create_by({"description"=>"slightly cloudy"})
SpecimenClarity.find_or_create_by({"description"=>"interface error"})
