Object.const_set("SpecimenCycle", Class.new(ActiveRecord::Base))
SpecimenCycle.find_or_create_by({"name"=>"S"})
SpecimenCycle.find_or_create_by({"name"=>"M"})
SpecimenCycle.find_or_create_by({"name"=>"L"})
SpecimenCycle.find_or_create_by({"name"=>"R"})
SpecimenCycle.find_or_create_by({"name"=>"S/M"})
SpecimenCycle.find_or_create_by({"name"=>"S/L"})
SpecimenCycle.find_or_create_by({"name"=>"L/M"})
SpecimenCycle.find_or_create_by({"name"=>"S/M/L"})
