Object.const_set("SpecimenTestType", Class.new(ActiveRecord::Base))
SpecimenTestType.find_or_create_by({"description"=>"Recut", "title"=>"Recut"})
SpecimenTestType.find_or_create_by({"description"=>"Breast", "title"=>"Breast"})
SpecimenTestType.find_or_create_by({"description"=>"Consult", "title"=>"Consult"})
SpecimenTestType.find_or_create_by({"description"=>"Cytology", "title"=>"Cytology"})
SpecimenTestType.find_or_create_by({"description"=>"Dermatology", "title"=>"Dermatology"})
SpecimenTestType.find_or_create_by({"description"=>"GI", "title"=>"GI"})
SpecimenTestType.find_or_create_by({"description"=>"Hematopathology", "title"=>"Hematopathology"})
SpecimenTestType.find_or_create_by({"description"=>"Mixed/General AP", "title"=>"Mixed/General AP"})
SpecimenTestType.find_or_create_by({"description"=>"Podiatry", "title"=>"Podiatry"})
SpecimenTestType.find_or_create_by({"description"=>"Professional Component", "title"=>"Professional Component"})
SpecimenTestType.find_or_create_by({"description"=>"Prostate", "title"=>"Prostate"})
SpecimenTestType.find_or_create_by({"description"=>"Send Out", "title"=>"Send Out"})
SpecimenTestType.find_or_create_by({"description"=>"Slide Prep", "title"=>"Slide Prep"})
SpecimenTestType.find_or_create_by({"description"=>"Special Stain", "title"=>"Special Stain"})
SpecimenTestType.find_or_create_by({"description"=>"TC Special Stain", "title"=>"TC Special Stain"})
SpecimenTestType.find_or_create_by({"description"=>"Urovysion", "title"=>"Urovysion"})
SpecimenTestType.find_or_create_by({"description"=>"IHC", "title"=>"IHC"})
SpecimenTestType.find_or_create_by({"description"=>"ISH", "title"=>"ISH"})
SpecimenTestType.find_or_create_by({"description"=>"Molecular", "title"=>"Molecular"})
SpecimenTestType.find_or_create_by({"description"=>"FISH Oncology", "title"=>"FISH Oncology"})
