Object.const_set("State", Class.new(ApplicationRecord))
State.find_or_create_by({"name"=>"ALABAMA", "abbreviation"=>"AL"})
State.find_or_create_by({"name"=>"ALASKA", "abbreviation"=>"AK"})
State.find_or_create_by({"name"=>"ARIZONA", "abbreviation"=>"AZ"})
State.find_or_create_by({"name"=>"ARKANSAS ", "abbreviation"=>"AR"})
State.find_or_create_by({"name"=>"CALIFORNIA", "abbreviation"=>"CA"})
State.find_or_create_by({"name"=>"COLORADO ", "abbreviation"=>"CO"})
State.find_or_create_by({"name"=>"CONNECTICUT", "abbreviation"=>"CT"})
State.find_or_create_by({"name"=>"DISTRICT OF COLUMBIA", "abbreviation"=>"DC"})
State.find_or_create_by({"name"=>"DELAWARE", "abbreviation"=>"DE"})
State.find_or_create_by({"name"=>"FLORIDA", "abbreviation"=>"FL"})
State.find_or_create_by({"name"=>"GEORGIA", "abbreviation"=>"GA"})
State.find_or_create_by({"name"=>"HAWAII", "abbreviation"=>"HI"})
State.find_or_create_by({"name"=>"IDAHO", "abbreviation"=>"ID"})
State.find_or_create_by({"name"=>"ILLINOIS", "abbreviation"=>"IL"})
State.find_or_create_by({"name"=>"INDIANA", "abbreviation"=>"IN"})
State.find_or_create_by({"name"=>"IOWA", "abbreviation"=>"IA"})
State.find_or_create_by({"name"=>"KANSAS", "abbreviation"=>"KS"})
State.find_or_create_by({"name"=>"KENTUCKY", "abbreviation"=>"KY"})
State.find_or_create_by({"name"=>"LOUISIANA", "abbreviation"=>"LA"})
State.find_or_create_by({"name"=>"MASSACHUSETTS", "abbreviation"=>"MA"})
State.find_or_create_by({"name"=>"MAINE", "abbreviation"=>"ME"})
State.find_or_create_by({"name"=>"MARYLAND", "abbreviation"=>"MD"})
State.find_or_create_by({"name"=>"MICHIGAN", "abbreviation"=>"MI"})
State.find_or_create_by({"name"=>"MINNESOTA", "abbreviation"=>"MN"})
State.find_or_create_by({"name"=>"MISSISSIPPI", "abbreviation"=>"MS"})
State.find_or_create_by({"name"=>"MISSOURI", "abbreviation"=>"MO"})
State.find_or_create_by({"name"=>"MONTANA ", "abbreviation"=>"MT"})
State.find_or_create_by({"name"=>"NEBRASKA ", "abbreviation"=>"NE"})
State.find_or_create_by({"name"=>"NEVADA", "abbreviation"=>"NV"})
State.find_or_create_by({"name"=>"NEW HAMPSHIRE", "abbreviation"=>"NH"})
State.find_or_create_by({"name"=>"NEW JERSEY", "abbreviation"=>"NJ"})
State.find_or_create_by({"name"=>"NEW MEXICO", "abbreviation"=>"NM"})
State.find_or_create_by({"name"=>"NEW YORK", "abbreviation"=>"NY"})
State.find_or_create_by({"name"=>"NORTH CAROLINA", "abbreviation"=>"NC"})
State.find_or_create_by({"name"=>"NORTH DAKOTA", "abbreviation"=>"ND"})
State.find_or_create_by({"name"=>"OHIO", "abbreviation"=>"OH"})
State.find_or_create_by({"name"=>"OKLAHOMA", "abbreviation"=>"OK"})
State.find_or_create_by({"name"=>"OREGON", "abbreviation"=>"OR"})
State.find_or_create_by({"name"=>"PENNSYLVANIA", "abbreviation"=>"PA"})
State.find_or_create_by({"name"=>"PUERTO RICO", "abbreviation"=>"PR"})
State.find_or_create_by({"name"=>"RHODE ISLAND", "abbreviation"=>"RI"})
State.find_or_create_by({"name"=>"SOUTH CAROLINA", "abbreviation"=>"SC"})
State.find_or_create_by({"name"=>"SOUTH DAKOTA", "abbreviation"=>"SD"})
State.find_or_create_by({"name"=>"TENNESSEE ", "abbreviation"=>"TN"})
State.find_or_create_by({"name"=>"TEXAS", "abbreviation"=>"TX"})
State.find_or_create_by({"name"=>"UTAH", "abbreviation"=>"UT"})
State.find_or_create_by({"name"=>"VERMONT ", "abbreviation"=>"VT"})
State.find_or_create_by({"name"=>"VIRGIN ISLANDS", "abbreviation"=>"VI"})
State.find_or_create_by({"name"=>"VIRGINIA", "abbreviation"=>"VA"})
State.find_or_create_by({"name"=>"WASHINGTON", "abbreviation"=>"WA"})
State.find_or_create_by({"name"=>"WEST VIRGINIA", "abbreviation"=>"WV"})
State.find_or_create_by({"name"=>"WISCONSIN", "abbreviation"=>"WI"})
State.find_or_create_by({"name"=>"WYOMING", "abbreviation"=>"WY"})
