Object.const_set("VariableField", Class.new(ApplicationRecord))
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$CassetteLabel$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Cassette$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$CassetteColor$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Clarity$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Color$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Cycle$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$JarLabel$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Pieces$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Size$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Slides$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Medium$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$PatientName$>", "global"=>true})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$BodySiteDescription$>", "global"=>true})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$SpecimenNotes$>", "global"=>true})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$SpecimenComments$>", "global"=>true})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$CO2$>"})
VariableField.find_or_create_by({"control_code_type_id"=>2, "variable"=>"<$Weight$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$ThinPrep$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$CytoSpin$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$Smears$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$FluidVolume$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$TimeOfFixation$>"})
VariableField.find_or_create_by({"control_code_type_id"=>6, "variable"=>"<$TimeOfProcessing$>"})
