Object.const_set("CassetteColor", Class.new(ActiveRecord::Base))
CassetteColor.find_or_create_by({"tps_description"=>"AQUA", "lab_is_cassette_color_id"=>1})
CassetteColor.find_or_create_by({"tps_description"=>"BLUE", "lab_is_cassette_color_id"=>2})
CassetteColor.find_or_create_by({"tps_description"=>"GRAY", "lab_is_cassette_color_id"=>3})
CassetteColor.find_or_create_by({"tps_description"=>"LILAC", "lab_is_cassette_color_id"=>4})
CassetteColor.find_or_create_by({"tps_description"=>"ORANGE", "lab_is_cassette_color_id"=>5})
CassetteColor.find_or_create_by({"tps_description"=>"PEACH", "lab_is_cassette_color_id"=>6})
CassetteColor.find_or_create_by({"tps_description"=>"PINK", "lab_is_cassette_color_id"=>7})
CassetteColor.find_or_create_by({"tps_description"=>"RED", "lab_is_cassette_color_id"=>8})
CassetteColor.find_or_create_by({"tps_description"=>"TAN", "lab_is_cassette_color_id"=>9})
CassetteColor.find_or_create_by({"tps_description"=>"WHITE", "lab_is_cassette_color_id"=>10})
CassetteColor.find_or_create_by({"tps_description"=>"YELLOW", "lab_is_cassette_color_id"=>11})
CassetteColor.find_or_create_by({"tps_description"=>"GREEN", "lab_is_cassette_color_id"=>12})
CassetteColor.find_or_create_by({"tps_description"=>"FLO PINK", "lab_is_cassette_color_id"=>13})
